### ISSUE TITLE
sysconf nproc_onln

### ISSUE THREAD

**Issue by wintersteiger** [lsds/sgx-lkl-musl#17]
See here: https://github.com/lsds/sgx-lkl-musl/blob/22c91c211aaf4048a4f034084bb7fa202bd6071c/src/conf/sysconf.c#L30
Should that be `nproc_onln` instead of `nproc_conf` or is it correct to ignore `nproc_onln` here?

@prp @davidchisnall

**Comment by prp** [comment]
I think that this is a musl change to work around the fact that LKL is unaware of the actual number of CPUs etc.

**Comment by wintersteiger** [comment]
Great, thanks!
